name: Send Secret to Gitee

on:
  push:
    branches:
      - main

jobs:
  send-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Secret to Gitee
        env:
          MY_SECRET: ${{ secrets.PYTHON_SCRIPT }}
          GITEE_TOKEN: 21cd48c8cb1546a257b0b5f4e3396a03
        run: |
          # 定义要创建的文件内容和文件名
          FILE_CONTENT="$MY_SECRET"
          FILE_NAME="secret.txt"
          # 构建 Gitee API 请求的 URL
          API_URL="https://gitee.com/api/v5/repos/yourancc/AA/contents/$FILE_NAME"
          # 构建请求的 JSON 数据
          JSON_DATA=$(jq -n --arg content "$(echo -n "$FILE_CONTENT" | base64)" '{message: "Add secret file", content: $content}')
          # 发送 POST 请求到 Gitee API
          curl -X POST -H "Authorization: token $GITEE_TOKEN" -H "Content-Type: application/json" -d "$JSON_DATA" $API_URL
