name: KEY_LOAD

on:
  workflow_dispatch:

jobs:
  record_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 设置 Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install PyGithub
        run: pip install PyGithub
      - name: Write script from secret
        run: |
          echo "${{ secrets.PYTHON_SCRIPT }}" > script.py
          chmod +x script.py
      - name: Use Secret in a script
        run: |
          # 通过 ${{ secrets.<SECRET_NAME> }} 语法获取 Secret 值
          API_KEY="${{ secrets.PYTHON_SCRIPT }}"
          echo "The API key is: $API_KEY"
