name: Increment Repository Variable

on:
  workflow_dispatch:  # 支持手动触发
  push:
    branches:
      - main  # 也可以在推送到 main 分支时触发

jobs:
  increment-counter:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "RUN_ID=2" >> "$GITHUB_ENV"
